# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"

In [1]:
txt="Hi there Sam!"
x=txt.split()
print(x)

['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

In [7]:
txt="Earth"
print(txt.format(an=12742))

Earth


## 3. In this nest dictionary grab the word "hello"

In [ ]:
d={'k1':[1,2,3]

In [32]:
d={'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print('d')

d


# Numpy

In [8]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [10]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

## 5. Create an array of all the even integers from 20 to 35

In [13]:
import numpy as np
array=np.arange(20,36,2)
print("Array of all the even from 30 to 70")
print(array)

Array of all the even from 30 to 70
[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [22]:
import numpy as np
a=np.arange(0,9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [29]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr1=np.concatenate((arr1,arr2))
print('arr')

arr


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [18]:
import pandas as pd
import pandas as pd
import numpy as np

exam_data  = {'name': ['Anastasia', 'Dima', 'Katherine', 'James', 'Emily', 'Michael', 'Matthew', 'Laura', 'Kevin', 'Jonas'],
        'score': [12.5, 9, 16.5, np.nan, 9, 20, 14.5, np.nan, 8, 19],
        'attempts': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'qualify': ['yes', 'no', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no', 'yes']}
labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

df = pd.DataFrame(exam_data , index=labels)
print("First three rows of the data frame:")
print(df.iloc[:3])

First three rows of the data frame:
        name  score  attempts qualify
a  Anastasia   12.5         1     yes
b       Dima    9.0         3      no
c  Katherine   16.5         2     yes


In [21]:
import pandas as pd
a=pd.date_range(start='1/1/2023',end='10/2/2023')
print(a)

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06', '2023-01-07', '2023-01-08',
               '2023-01-09', '2023-01-10',
               ...
               '2023-09-23', '2023-09-24', '2023-09-25', '2023-09-26',
               '2023-09-27', '2023-09-28', '2023-09-29', '2023-09-30',
               '2023-10-01', '2023-10-02'],
              dtype='datetime64[ns]', length=275, freq='D')


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [30]:
import pandas as pd
a=pd.date_range(start='1/1/2023',end='10/2/2023')
print('a')

a


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [31]:
lists=[[1,'aaa',22],[2,'bbb,25'],[3,'ccc',24]]
import pandas as pd
lst=[[1,'aaa',22],[2,'bbb,25'],[3,'ccc',24]]
df=pd.DataFrame(lst)
print('df')

df
